sudo: false
language: ruby

cache:
  directories:
    - ~/.ccache

os:
  - linux

env:
  - CI=1 IMAGEMAGICK_VERSION=6.8.9-10

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.1

before_install:
  - source before_install_$TRAVIS_OS_NAME.sh
